version: '{build}'
clone_folder: c:\workspace\OpenRTM-aist
platform:
- x64
configuration:
  - Release
environment:
  omniorb: omniORB-4.2.3
  cmake_flags: -DOMNI_VERSION=42 -DOMNI_MINOR=3 -DOMNITHREAD_VERSION=41 -DCORBA=omniORB -DSSL_ENABLE=ON -DOBSERVER_ENABLE=ON
  matrix:
    - cmake_generator: Visual Studio 14 2015          # CMake -G
      cmake_archtecture: x64                          # CMake -A
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015 # Choices: Appveyor depend
      python: 37-x64                                  # Choices: Appveyor depend
    - cmake_generator: Visual Studio 12 2013
      cmake_archtecture: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      python: 37-x64
    - cmake_generator: Ninja
      cmake_archtecture: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      python: 37-x64
      MSVC_HOME: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community"

matrix:
  fast_finish: true

init:
# change to ja-JP is too slow
#  - ps: Set-WinSystemLocale ja-JP
#  - ps: Start-Sleep -s 5
#  - ps: Restart-Computer
  - git config --global core.autocrlf false
  - ps: $Env:APPVEYOR_BUILD_WORKER_IMAGE
  - ps: $Env:cmake_generator
  - ps: $Env:cmake_archtecture
  - ps: |
      switch ($Env:cmake_generator) {
        "Visual Studio 12 2013" { $vc_tool = "120" }
        "Visual Studio 14 2015" { $vc_tool = "140" }
        "Visual Studio 15 2017" { $vc_tool = "140" }
        "Visual Studio 16 2019" { $vc_tool = "140" }
        default { $vc_tool = "140" }
      }
      $Env:omni = "${Env:omniorb}-${Env:cmake_archtecture}-vc${vc_tool}-py$(${Env:python}.Split("-")[0])"
      $omni_url = "http://tmp.openrtm.org/pub/omniORB/win32/${Env:omniorb}/${Env:omni}.zip"
      $Env:Path = "C:\Python${Env:python};c:\Python${Env:python}\scripts;${Env:Path}"
  - ps: $Env:omni
  - python --version
  - cmake --version

install:
  - ps: |
      # prepare omniORB (restored from cache if cached)
      if(-NOT (Test-Path "C:/omni/${Env:omni}")){
        Invoke-WebRequest -Uri $omni_url -OutFile ${Env:TEMP}\a.zip
        Expand-Archive -Path ${Env:TEMP}\a.zip -DestinationPath "C:/omni"
      }

before_build:
  - echo cmake %cmake_flags% -DORB_ROOT=C:/omni/%omni% -G "%cmake_generator%" -A "%cmake_archtecture%" -S . -B ../build
  -      cmake %cmake_flags% -DORB_ROOT=C:/omni/%omni% -G "%cmake_generator%" -A "%cmake_archtecture%" -S . -B ../build

# sample: cmake build script for cmake 3.15.
#build_script:
# - ps: $Env:nproc = (Get-WmiObject -Class Win32_Processor).NumberOfLogicalProcessors
# - echo cmake --build ../build -j --config Release -- /p:CL_MPCount=%nproc% -verbosity:minimal
# - cmake --build ../build -j --config Release -- /p:CL_MPCount=%nproc% -verbosity:minimal

build:
  project: C:\workspace\build\OpenRTM_aist.sln
  verbosity: minimal
  parallel: true

for:
-
  matrix:
    only:
      - cmake_generator: Ninja

  before_build:
    - ninja --version
    - call "%MSVC_HOME%\VC\Auxiliary\Build\vcvarsall.bat" %cmake_archtecture%
    # clang for code analysis.
    - echo cmake %cmake_flags% -DORB_ROOT=C:/omni/%omni% -G "%cmake_generator%" -DCMAKE_CXX_COMPILER="clang-cl.exe" -DCMAKE_LINKER="lld-link.exe" -DCMAKE_BUILD_TYPE=Release -S . -B ../build
    -      cmake %cmake_flags% -DORB_ROOT=C:/omni/%omni% -G "%cmake_generator%" -DCMAKE_CXX_COMPILER="clang-cl.exe" -DCMAKE_LINKER="lld-link.exe" -DCMAKE_BUILD_TYPE=Release -S . -B ../build

  build_script:
    - cmake --build ../build

cache:
  - C:/omni -> .appveyor.yml

only_commits:
  files:
    - .appveyor.yml
    - CMakeLists.txt
    - etc/
    - examples/
    - src/
    - utils/
