version: '{build}'
clone_folder: c:\workspace\OpenRTM-aist
image:
- Visual Studio 2013
#- Visual Studio 2015
- Visual Studio 2017
platform:
- x64
environment:
  omniorb: omniORB-4.2.3
  cmake_flgas: -DOMNI_VERSION=42 -DOMNI_MINOR=3 -DOMNITHREAD_VERSION=41 -DCORBA=omniORB -DSSL_ENABLE=ON -DOBSERVER_ENABLE=ON
  matrix:
    - arch: Win64
matrix:
  fast_finish: true

init:
# change to ja-JP is too slow
#  - ps: Set-WinSystemLocale ja-JP
#  - ps: Start-Sleep -s 5
#  - ps: Restart-Computer
  - git config --global core.autocrlf false
  - ps: $Env:arch
  - ps: $Env:APPVEYOR_BUILD_WORKER_IMAGE
  - ps: |
      if("$Env:APPVEYOR_BUILD_WORKER_IMAGE" -eq "Visual Studio 2017") {
        $Env:generator = "`"Visual Studio 15 2017 $Env:arch`""
        $vc = "vc141"
        $python = "37-x64"
      }
      if("$Env:APPVEYOR_BUILD_WORKER_IMAGE" -eq "Visual Studio 2015") {
        $Env:generator = "`"Visual Studio 14 2015 $Env:arch`""
        $vc = "vc14"
        $python = "27"
      }
      if("$Env:APPVEYOR_BUILD_WORKER_IMAGE" -eq "Visual Studio 2013") {
        $Env:generator = "`"Visual Studio 12 2013 $Env:arch`""
        $vc = "vc12"
        $python = "27"
      }
      $Env:omni = "${Env:omniorb}-$(${Env:arch}.ToLower())-${vc}"
      $Env:omni_url = "http://tmp.openrtm.org/pub/omniORB/win32/${Env:omniorb}/${Env:omni}-py$(${python}.Split("-")[0]).zip"
      $Env:Path = "C:\Python${python};c:\Python${python}\scripts;${Env:Path}"
  - ps: $Env:generator
  - ps: $Env:omni
  - python --version

before_build:
  - ps: |
      # prepare omniORB (restored from cache if cached)
      if(-NOT (Test-Path "C:/omni/${Env:omni}")){
        Invoke-WebRequest -Uri $Env:omni_url -OutFile ${Env:TEMP}\a.zip
        Expand-Archive -Path ${Env:TEMP}\a.zip -DestinationPath "C:/omni"
      }

      # workalound
      New-Item -ItemType SymbolicLink -Path $(PWD) -Name src\lib\coil\common\coil -Target src\lib\coil\common
      New-Item -ItemType SymbolicLink -Path $(PWD) -Name utils\rtm-skelwrapper\yat.py -Target build\yat.py
  - cmake --version
  - cmake %cmake_flgas% -DORB_ROOT=C:/omni/%omni% -G %generator% -S . -B../build

build_script:
  - ps: $Env:nproc = (Get-WmiObject -Class Win32_Processor).NumberOfLogicalProcessors + 1
  - ps: $Env:nproc
  - cmake --build ../build -j %nproc% --config Release -- -verbosity:minimal

#build (.sln) is slower than build_script (cmake)
#build:
#  project: C:\workspace\build\OpenRTM_aist.sln
#  verbosity: minimal
#  parallel: true

cache:
  - C:/omni -> appveyor.yml

only_commits:
  files:
    - appveyor.yml
    - CMakeLists.txt
    - etc/
    - examples/
    - src/
    - utils/
