trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - azure-pipelines.yml
    - .azure-pipelines
    - CMakeLists.txt
    - etc/
    - examples/
    - src/
    - utils/

pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - azure-pipelines.yml
    - .azure-pipelines
    - CMakeLists.txt
    - etc/
    - examples/
    - src/
    - utils/

variables:
  omniorb: omniORB-4.2.4-x64-vc140-py37
  omniorbUrl: https://openrtm.org/pub/omniORB/win32/omniORB-4.2.4
  ros2: ros2-dashing-20191213-windows-amd64
  ros2Url: https://github.com/ros2/ros2/releases/download/release-dashing-20191213/
  ninja: ninja-win
  ninjaUrl: https://github.com/ninja-build/ninja/releases/download/v1.10.2/
  ninjaVersion: 1.10.2

jobs:
  - job: Build
    strategy:
      matrix:
        vs2019:
          imageVersion: 'windows-2019'
        vs2017:
          imageVersion: 'vs2017-win2016'

    pool:
      vmImage: $(imageVersion)

    steps:
      - template: .azure-pipelines/openrtm-build-environment.yml
        parameters:
          omniorb: $(omniorb)
          omniorbUrl: $(omniorbUrl)
          ros2: $(ros2)
          ros2Url: $(ros2Url)
          ninja: $(ninja)
          ninjaUrl: $(ninjaUrl)
          ninjaVersion: $(ninjaVersion)

      - task: CMake@1
        env:
          PYTHONPATH: '$(Pipeline.Workspace)\ros2-windows\Lib\site-packages;$(PYTHONPATH)'
          ROS_DISTRO: 'dashing'
          ROS_PYTHON_VERSION: '3'
          ROS_VERSION: '2'
          AMENT_PREFIX_PATH: '$(Pipeline.Workspace)\ros2-windows'
          CMAKE_PREFIX_PATH: '$(Pipeline.Workspace)\ros2-windows'
          PKG_CONFIG_PATH: '$(Pipeline.Workspace)\ros2-windows\lib\pkgconfig'
          COLCON_PREFIX_PATH: '$(Pipeline.Workspace)\ros2-windows'
        inputs:
          workingDirectory: 'build'
          cmakeArgs:
            -A x64
            -DRTM_VC_VER=vc14
            -DOMNI_VERSION=42
            -DOMNI_MINOR=3
            -DOMNITHREAD_VERSION=41
            -DCORBA=omniORB
            -DORB_ROOT=$(Pipeline.Workspace)\$(omniorb)
            -DOBSERVER_ENABLE=ON
            -DSSL_ENABLE=ON
            -DFASTRTPS_ENABLE=ON
            -DROS2_ENABLE=ON
            $(Build.SourcesDirectory)

      - task: VSBuild@1
        inputs:
          solution: 'build/OpenRTM_aist.sln'
          configuration: 'Release'
          maximumCpuCount: true
          createLogFile: true
          logFileVerbosity: 'minimal'

  - job: Analyze
    pool:
      vmImage: 'windows-latest'

    variables:
      vcPath: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC'

    steps:
      - template: .azure-pipelines/openrtm-build-environment.yml
        parameters:
          omniorb: $(omniorb)
          omniorbUrl: $(omniorbUrl)
          ros2: $(ros2)
          ros2Url: $(ros2Url)
          ninja: $(ninja)
          ninjaUrl: $(ninjaUrl)
          ninjaVersion: $(ninjaVersion)

      - script: |
          call "$(vcPath)\Auxiliary\Build\vcvars64.bat"
          cmake ^
            -B $(Build.SourcesDirectory)/build ^
            -G Ninja ^
            -DCMAKE_MAKE_PROGRAM=$(Pipeline.Workspace)\$(ninja)\ninja.exe ^
            -DCMAKE_C_COMPILER:FILEPATH=clang-cl.exe ^
            -DCMAKE_CXX_COMPILER:FILEPATH=clang-cl.exe ^
            -DCMAKE_LINKER:FILEPATH=lld-link.exe ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DRTM_VC_VER=vc14 ^
            -DOMNI_VERSION=42 ^
            -DOMNI_MINOR=3 ^
            -DOMNITHREAD_VERSION=41 ^
            -DCORBA=omniORB ^
            -DORB_ROOT=$(Pipeline.Workspace)\$(omniorb) ^
            -DOBSERVER_ENABLE=ON ^
            -DSSL_ENABLE=ON ^
            -DFASTRTPS_ENABLE=ON ^
            -DROS2_ENABLE=ON ^
            $(Build.SourcesDirectory)
          cmake --build $(Build.SourcesDirectory)\build
        displayName: Analyze by Clang
        env:
          CFLAGS: -m64 -fdiagnostics-absolute-paths
          CXXFLAGS: -m64 -fdiagnostics-absolute-paths
          PYTHONPATH: '$(Pipeline.Workspace)\ros2-windows\Lib\site-packages;$(PYTHONPATH)'
          ROS_DISTRO: 'dashing'
          ROS_PYTHON_VERSION: '3'
          ROS_VERSION: '2'
          AMENT_PREFIX_PATH: '$(Pipeline.Workspace)\ros2-windows'
          CMAKE_PREFIX_PATH: '$(Pipeline.Workspace)\ros2-windows'
          PKG_CONFIG_PATH: '$(Pipeline.Workspace)\ros2-windows\lib\pkgconfig'
          COLCON_PREFIX_PATH: '$(Pipeline.Workspace)\ros2-windows'
