name: OpenRTM on Linux

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu_1604, ubuntu_1804, debian_10]
    steps:
    - uses: actions/checkout@v1
    - name: Build OpenRTM
      run: docker build .. --file scripts/${{matrix.os}}/Dockerfile --tag openrtm:${{matrix.os}}-$(date +%s)
